site:
  title: Debezium Documentation
  # the 404, site-map, and canonical urls are only generated when a url is defined
  url: https://www.debezium.io/documentation
  start_page: reference::index.adoc

content:
  sources:
    - url: https://github.com/debezium/debezium.git
      start_path: documentation
      branches:
        - '0.9'
        - '0.10'
        - '1.1'
        - 'master'
      tags:
        - 'v1.0.0.Final'

ui:
  bundle:
    url: /site/_antora/ui-bundle.zip
    snapshot: true
  supplemental_files: /site/_antora/supplemental_ui
  output_dir: debezium-antora

runtime:
  fetch: true

output:
  dir: /site/_site/documentation

# Global asciidoc attributes here, used across all versions of documentation
asciidoc:
  attributes:
    prodname: 'Debezium'
    context: 'debezium'
    jira-url: 'https://issues.redhat.com'
    # because of how handlebars templates work with page.attributes, this must be prefixed with "page-"
    page-copyright-year: '2020'
